version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
